name: wlss-bff-qa

services:
  app:
    build:
      context: ../../..  # path from the corrent file to the project root dir
      dockerfile: envs/qa/deploy/Dockerfile  # path from the project root dir to the Dockerfile
    environment:
      - WLSS_ENV=qa/deploy
    volumes:
      - .env:/wlss-bff/envs/qa/deploy/.env
    entrypoint: >
      bash -c "
        gunicorn --config=envs/qa/deploy/gunicorn/config.py
      "

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - 8000:8000
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
