name: Use buildx cache
description: Shortcut for several reusable steps which allow to get/put Docker cache from/in GitHub Cache

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          buildx-${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-${{ github.ref_name }}
          buildx-${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-${{ github.event.repository.default_branch }}
